const LOADING_RESERVATIONS = 'LOADING_RESERVATIONS';
const FETCH_RESERVATIONS = 'FETCH_RESERVATIONS';
const ADD_RESERVATION = 'ADD_RESERVATION';
const EDIT_RESERVATION = 'EDIT_RESERVATION';
const DELETE_RESERVATION = 'DELETE_RESERVATION';
const IS_SEARCHING_RESERVATIONS = 'IS_SEARCHING_RESERVATIONS';
const SEARCH_RESERVATIONS = 'SEARCH_RESERVATIONS';
const DELETE_SEARCH_RESERVATION = 'DELETE_SEARCH_RESERVATION';
const EDIT_SEARCH_RESERVATION = 'EDIT_SEARCH_RESERVATION';

export default {
   LOADING_RESERVATIONS,
   FETCH_RESERVATIONS,
   ADD_RESERVATION,
   EDIT_RESERVATION,
   DELETE_RESERVATION,
   IS_SEARCHING_RESERVATIONS,
   SEARCH_RESERVATIONS,
   DELETE_SEARCH_RESERVATION,
   EDIT_SEARCH_RESERVATION
}
