const LOADING_EMPLOYEES = 'LOADING_EMPLOYEES';
const FETCH_EMPLOYEES = 'FETCH_EMPLOYEES';
const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
const EDIT_EMPLOYEE = 'EDIT_EMPLOYEE';
const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
const IS_SEARCHING_EMPLOYEES = 'IS_SEARCHING_EMPLOYEES';
const SEARCH_EMPLOYEES = 'SEARCH_EMPLOYEES';
const DELETE_SEARCH_EMPLOYEE = 'DELETE_SEARCH_EMPLOYEE';
const EDIT_SEARCH_EMPLOYEE = 'EDIT_SEARCH_EMPLOYEE';

export default {
   LOADING_EMPLOYEES,
   FETCH_EMPLOYEES,
   ADD_EMPLOYEE,
   EDIT_EMPLOYEE,
   DELETE_EMPLOYEE,
   IS_SEARCHING_EMPLOYEES,
   SEARCH_EMPLOYEES,
   DELETE_SEARCH_EMPLOYEE,
   EDIT_SEARCH_EMPLOYEE
}
