const FETCH_SERVICES = 'FETCH_SERVICES';
const ADD_SERVICE = 'ADD_SERVICE';
const EDIT_SERVICE = 'EDIT_SERVICE';
const DELETE_SERVICE = 'DELETE_SERVICE';

export default {
   FETCH_SERVICES,
   ADD_SERVICE,
   EDIT_SERVICE,
   DELETE_SERVICE
}
