const LOADING_SERVICES = 'LOADING_SERVICES';
const FETCH_SERVICES = 'FETCH_SERVICES';
const ADD_SERVICE = 'ADD_SERVICE';
const EDIT_SERVICE = 'EDIT_SERVICE';
const DELETE_SERVICE = 'DELETE_SERVICE';
const IS_SEARCHING_SERVICES = 'IS_SEARCHING_SERVICES';
const SEARCH_SERVICES = 'SEARCH_SERVICES';
const DELETE_SEARCH_SERVICE = 'DELETE_SEARCH_SERVICE';
const EDIT_SEARCH_SERVICE = 'EDIT_SEARCH_SERVICE';

export default {
   LOADING_SERVICES,
   FETCH_SERVICES,
   ADD_SERVICE,
   EDIT_SERVICE,
   DELETE_SERVICE,
   IS_SEARCHING_SERVICES,
   SEARCH_SERVICES,
   DELETE_SEARCH_SERVICE,
   EDIT_SEARCH_SERVICE
}
