const LOADING_CLIENTS = 'LOADING_CLIENTS';
const FETCH_CLIENTS = 'FETCH_CLIENTS';
const ADD_CLIENT = 'ADD_CLIENT';
const EDIT_CLIENT = 'EDIT_CLIENT';
const DELETE_CLIENT = 'DELETE_CLIENT';
const IS_SEARCHING_CLIENTS = 'IS_SEARCHING_CLIENTS';
const SEARCH_CLIENTS = 'SEARCH_CLIENTS';
const DELETE_SEARCH_CLIENT = 'DELETE_SEARCH_CLIENT';
const EDIT_SEARCH_CLIENT = 'EDIT_SEARCH_CLIENT';
const IMPORT_CLIENTS = 'IMPORT_CLIENTS';

export default {
   LOADING_CLIENTS,
   FETCH_CLIENTS,
   ADD_CLIENT,
   EDIT_CLIENT,
   DELETE_CLIENT,
   IS_SEARCHING_CLIENTS,
   SEARCH_CLIENTS,
   DELETE_SEARCH_CLIENT,
   EDIT_SEARCH_CLIENT,
   IMPORT_CLIENTS
}
